services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    phpdish_post.manager.post:
        class: PHPDish\Bundle\PostBundle\Service\PostManager
        public: true
        arguments:
            - ''
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '@markdown.parser'

    phpdish_post.manager.category:
        class: PHPDish\Bundle\PostBundle\Service\CategoryManager
        public: true
        arguments:
            - ''
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '@phpdish_payment.manager.payment'
            - '@router'
            - '@translator'

    phpdish_post.manager.book:
        class: PHPDish\Bundle\PostBundle\Service\BookManager
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@phpdish_post.manager.post'
            - '@phpdish_post.manager.category'

    phpdish_post.manager.post.comment:
        class: PHPDish\Bundle\PostBundle\Service\CommentManager
        public: true
        arguments:
            - ''
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - "@phpdish_cms.body_processor"

    phpdish_post.form.type.post:
         class: PHPDish\Bundle\PostBundle\Form\Type\PostType
         arguments: ['@phpdish_post.manager.category']
         tags:
             - { name: form.type }

    phpdish_post.security.post_voter:
        class: PHPDish\Bundle\PostBundle\Security\PostVoter
        arguments: ['@security.access.decision_manager']
        tags:
             - { name: security.voter}
        public: false


    phpdish_post.security.comment_voter:
        class: PHPDish\Bundle\PostBundle\Security\CommentVoter
        arguments: ['@security.access.decision_manager']
        tags:
             - { name: security.voter}
        public: false

    phpdish_post.security.category_voter:
        class: PHPDish\Bundle\PostBundle\Security\CategoryVoter
        arguments: ['@security.access.decision_manager']
        tags:
             - { name: security.voter}
        public: false

    phpdish_post.avatar_generator.category:
        class: PHPDish\Bundle\ResourceBundle\AvatarGenerator\AvatarGenerator
        arguments: ['@phpdish_media.file_manager', '@phpdish_media.file_namer']

    phpdish_post.event_listener.category_persist:
        class: PHPDish\Bundle\PostBundle\EventListener\CategoryPersistListener
        arguments: ['@phpdish_post.avatar_generator.category']
        tags:
             - { name: kernel.event_listener, event: category.pre_persist, method: onCategoryPersist}
        public: false

    phpdish_post.event_listener.payment:
        class: PHPDish\Bundle\PostBundle\EventListener\PaymentListener
        arguments: ['@phpdish_post.manager.category', '@phpdish_payment.manager.wallet']
        tags:
             - { name: kernel.event_listener, event: payment.paid, method: onPaymentPaid}
        public: false

    phpdish_post.twig_extension.post:
        class: PHPDish\Bundle\PostBundle\Twig\PostExtension
        public: false
        arguments:
            - "@phpdish_post.manager.category"
            - "@phpdish_post.manager.post"
            - "@phpdish_post.manager.post.comment"
        tags:
            - {name: twig.extension}

    phpdish_post.doctrine.orm.entity_listener.post:
        class: PHPDish\Bundle\PostBundle\EventListener\PostListener
        public: false
        arguments: ['@phpdish_post.manager.post', '@phpdish_user.manager.user']
        tags:
            - {name: doctrine.orm.entity_listener, entity: PHPDish\Bundle\PostBundle\Model\Post, event: postPersist, method: postPersist}

    PHPDish\Bundle\PostBundle\Controller\:
         resource: "../../Controller"
         arguments:
              $configuration: '@phpdish_resource.configuration.phpdish_post'
         tags: ['controller.service_arguments']