# PHPDish Mention Adapter
services:
    phpdish.security.password_encoder.generic:
        class: PHPDish\Bundle\CoreBundle\Security\Core\Encoder\GenericPasswordEncoder
        arguments: ['%security.password_encoder_strength%']

    phpdish.theme.context.generic:
        class: PHPDish\Bundle\CoreBundle\Theme\Context\GenericThemeContext
        arguments: ['@sylius.repository.theme', '%theme.current_theme%']

    phpdish.mention.adapter:
        class: PHPDish\Bundle\UserBundle\Mention\Adapter
        arguments: ['@phpdish.manager.user', '@router']

    phpdish.mention.parser:
        class: PHPDish\Component\Mention\MentionParser
        arguments: ['@phpdish.mention.adapter']

    phpdish.body_processor:
        class: PHPDish\Component\Core\BodyProcessor\BodyProcessor
        arguments:
            - "@markdown.parser"
            - "@phpdish.mention.parser"
            - "@exercise_html_purifier.default"

    phpdish.http_client:
        class: GuzzleHttp\Client
        arguments:
            - {verify: false}

    phpdish.qcloud_factory:
        class: PHPDish\Component\QCloud\QCloudFactory
        arguments: ['%qcloud.secret_id%', '%qcloud.secret_key%']

    phpdish.pinyin_translator:
        class: Overtrue\Pinyin\Pinyin

    ## 安全裁切html
    phpdish.html_chunker:
        class: PHPDish\Component\Util\HtmlChunker
        arguments: ['@exercise_html_purifier.default']

    ## 搜索服务，如果需要其它服务可以自行替换
    phpdish.searcher:
        class: PHPDish\Bundle\CoreBundle\Search\AlgoliaSearch
        public: true
        arguments:
            - "@algolia.indexer"
            - "@doctrine.orm.entity_manager"