services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # 订阅者和监听者
    phpdish_core.event_listener.pjax:
         class: PHPDish\Component\Pjax\EventListener\KernelResponseListener
         arguments: ['@phpdish_core.pjax.helper']
         public: false
         tags:
            - { name: kernel.event_listener, event: 'kernel.response', method: 'onKernelResponse'}

    phpdish_core.event_listener.core.kernel:
         class: PHPDish\Bundle\CoreBundle\EventListener\KernelExceptionListener
         arguments: ['@security.token_storage', '@security.authorization_checker', '@router']
         public: false
         tags:
            - { name: kernel.event_listener, event: 'kernel.exception', method: 'onKernelException', priority: 1}

    # 站点语言订阅者
    phpdish_core.event_subscriber.locale:
        class: PHPDish\Bundle\CoreBundle\EventListener\LocaleSubscriber
        arguments: ['@phpdish_core.locale_manager', '@session']
        tags: ['kernel.event_subscriber']

    phpdish_core.event_subscriber.user:
        class: PHPDish\Bundle\CoreBundle\EventListener\UserSubscriber
        arguments:
            - '@fos_user.user_manager'
            - '@fos_message.composer'
            - '@fos_message.sender'
            - '@translator'
            - '%chat.sender%'
            - '%chat.register_message%'
        tags: ['kernel.event_subscriber']

    phpdish_core.doctrine.orm.entity_listener.topic:
        class: PHPDish\Bundle\CoreBundle\EventListener\TopicListener
        public: false
        arguments: ['@phpdish_forum.manager.topic', '@phpdish_user.manager.user']
        tags:
            - {name: doctrine.orm.entity_listener, entity: PHPDish\Bundle\CoreBundle\Model\Topic, event: postPersist, method: postPersist}

    phpdish_core.event_subscriber.point:
        class: PHPDish\Bundle\CoreBundle\EventListener\PointSubscriber
        autowire: true
        tags: ['kernel.event_subscriber']

    PHPDish\Bundle\CoreBundle\EventListener\Notification\:
         resource: '../../../EventListener/Notification/*'