services:
#    phpdish.plugin.plugin_manager:
#         class: PHPDish\Bundle\CoreBundle\Plugin\PluginManager
#         arguments: ['@service_container', '%kernel.project_dir%']

    phpdish.plugin.finder:
        class: PHPDish\Bundle\CoreBundle\Plugin\Finder\PluginFinder
        arguments: ['%kernel.project_dir%']

    phpdish.plugin.finder.cached:
        class: PHPDish\Bundle\CoreBundle\Plugin\Finder\CachedPluginFinder
        arguments: ['%kernel.cache_dir%/phpdish_plugins.php', '@phpdish.plugin.finder']

    phpdish.plugin.route_loader:
        class: PHPDish\Bundle\CoreBundle\Plugin\Routing\RoutingLoader
        tags:
            - {name: routing.loader}

    phpdish.plugin.listener_registry:
        class: PHPDish\Bundle\CoreBundle\Plugin\ListenerRegistry

    phpdish.plugin.cache.warmer.plugin_paths:
        class: PHPDish\Bundle\CoreBundle\Plugin\Cache\PluginPathsCacheWarmer
        arguments: ['@phpdish.plugin.finder']
        tags:
           - {name: kernel.cache_warmer}

    phpdish.plugin.cache.clearer.plugin_paths:
        class: PHPDish\Bundle\CoreBundle\Plugin\Cache\PluginPathsCacheClearer
        tags:
           - {name: kernel.cache_clearer, priority: 999}