PHPDish\Bundle\PostBundle\Entity\Post:
    exclusion_policy: ALL
    xml_root_name: post
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed, searchable]
        title:
            expose: true
            type: string
            groups: [Default, Detailed, searchable]
        body:
            expose: true
            type: string
            groups: [Default, Detailed, searchable]

        originalBody:
            expose: true
            type: string
            groups: [Default, Detailed]
        cover:
            expose: true
            type: integer
            groups: [Default, Detailed]
        recommended:
            expose: true
            type: boolean
            groups: [Default, Detailed]
        commentCount:
            expose: true
            type: integer
            groups: [Default, Detailed]
        viewCount:
            expose: true
            type: integer
            groups: [Default, Detailed]
        voteCount:
            expose: true
            type: integer
            groups: [Default, Detailed]
        enabled:
            expose: true
            type: boolean
            groups: [Default, Detailed]
        createdAt:
            expose: true
            type: DateTime
            groups: [Detailed]
        updatedAt:
            expose: true
            type: DateTime
            groups: [Detailed]
        user:
            expose: true
            type: PHPDish\Bundle\UserBundle\Model\User
            groups: [Detailed]
        category:
            expose: true
            type: PHPDish\Bundle\UserBundle\Model\User
            groups: [Detailed]
