imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: '@PHPDishAdminBundle/Resources/config/config.yml' }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: zh_CN

    app.dir.media: '%kernel.project_dir%/web/media'
    app.dir.uploads: '%kernel.project_dir%/web/media/uploads'
    app.dir.avatar: '%kernel.project_dir%/web/media/uploads/avatar'
    app.path.media: '/media'
    app.path.uploads: '/media/uploads'
    app.path.avatar: '/media/uploads/avatar'

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer:
      enable_annotations: true
      enabled: true
      cache: serializer.mapping.cache.apc

    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/web/build/manifest.json'
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
#        entity_managers:
#            default:
#                metadata_cache_driver: apc
#                result_cache_driver: apc
#                query_cache_driver: apc


doctrine_migrations:
    dir_name: "%kernel.root_dir%/migrations"
    namespace: PHPDish\Migrations
    table_name: phpdish_migrations
    name: PHPDish Migrations

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

monolog:
    channels: ['notes']
    handlers:
        notes:
            type: stream
            path: '%kernel.logs_dir%/notes.log'
            level: debug
            channels: ['notes']

# KNP Gaufrette:
knp_gaufrette:
    adapters:
        uploads:
            local:
                directory: '%app.dir.uploads%'
                create: true
        avatar:
            local:
                directory: '%app.dir.avatar%'
                create: true

    filesystems:
        local:
          adapter: uploads
          alias: phpdish.filesystem.uploads
        avatar:
          adapter: avatar
          alias: phpdish.filesystem.avatar

knp_menu:
    twig:
        template: KnpMenuBundle::menu.html.twig
    templating: false
    default_renderer: twig

# Liip Imagine
liip_imagine:
    loaders:
        default:
            filesystem:
                data_root:
                  - '%app.dir.uploads%'
                  - '%app.dir.avatar%'

    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        # the name of the "filter set"
        middle_square:
            quality: 75
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
                background: { size: [120, 120], position: center, color: '#ffffff' }

        middle_rectangle:
            quality: 75
            filters:
                thumbnail: { size: [220, 300], mode: outbound }
                background: { size: [220, 300], position: center, color: '#ffffff' }
## FOSUser
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: PHPDish\Bundle\UserBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

# FOSRest
fos_rest:
    routing_loader:
        default_format: json
    view:
#        mime_types:
#            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1', 'application/json;version=1.2']
        view_response_listener: false
        formats:
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig

    format_listener:
        rules:
            - { path: ^/, priorities: [ html, json ], fallback_format: ~, prefer_extension: true }

# FOSMessage
fos_message:
    db_driver: orm
    thread_class: PHPDish\Bundle\ChatBundle\Entity\Thread
    message_class: PHPDish\Bundle\ChatBundle\Entity\Message

# 社交网站登录
hwi_oauth:
    http_client:
          timeout: 10
          verify_peer: false
          ignore_errors: false

    firewall_names:
        - 'main'

    resource_owners:
        weibo:
            type: sina_weibo
            client_id: '%oauth.weibo.client_id%'
            client_secret: '%oauth.weibo.client_secret%'
            scope: 'all'

        github:
            type: github
            client_id: '%oauth.github.client_id%'
            client_secret: '%oauth.github.client_secret%'
            scope: 'user:email,public_repo'

        qq:
            type: qq
            client_id: '%oauth.qq.client_id%'
            client_secret: '%oauth.qq.client_secret%'
            scope: 'get_user_info'

httplug:
    plugins:
        logger: ~
    clients:
        default:
            factory: 'httplug.factory.guzzle6'
            plugins: ['httplug.plugin.logger']
            config:
                verify: false
                timeout: 20


algolia:
    application_id: '%algolia.application_id%'
    api_key: '%algolia.api_key%'
    catch_log_exceptions: true
    index_name_prefix: staging


sonata_seo:
    page:
        title:            '%phpdish.site.title%'
        metas:
            name:
                keywords:             '%phpdish.site.keywords%'
                description:          '%phpdish.site.description%'
                apple-mobile-web-app-title: '%phpdish.site.title%'

            property:
                'og:site_name':      '%phpdish.site.title%'
                'og:description':    '%phpdish.site.description%'

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7


# Media
php_dish_media:
    maps:
        avatar:
            filesystem_service: phpdish.filesystem.avatar
            path: '%app.path.avatar%'

# 支付
php_dish_payment:
    youzan:
      client_id: '%youzan.client_id%'
      client_secret: '%youzan.client_secret%'
      kdt_id: '%youzan.kdt_id%'
