services:

    phpdish_theme.file_locator:
        class: PHPDish\Bundle\ThemeBundle\Templating\Loader\FileLocator
        parent: file_locator
        calls:
           - {method: setThemeManager, arguments: ['@phpdish_theme.theme_manager']}
           - {method: setKernel, arguments: ['@kernel']}

    phpdish_theme.templating_locator:
        class: PHPDish\Bundle\ThemeBundle\Templating\Loader\TemplateLocator
        arguments: ['@phpdish_theme.file_locator', '%kernel.cache_dir%']
        calls:
           - {method: setThemeManager, arguments: ['@phpdish_theme.theme_manager']}

    phpdish_theme.templating_finder:
        class: PHPDish\Bundle\ThemeBundle\CacheWarmer\TemplateFinder
        arguments:
          - '@phpdish_theme.theme_manager'
          - '@kernel'
          - '@templating.filename_parser'
          - '%kernel.root_dir%/Resources'
          - '%phpdish_theme.theme_dir%'

    phpdish_theme.templating.cache_warmer.template_paths:
        class: PHPDish\Bundle\ThemeBundle\CacheWarmer\TemplatePathsCacheWarmer
        arguments: ['@phpdish_theme.theme_manager', '@phpdish_theme.templating_finder', '@phpdish_theme.templating_locator']
        tags: [{name: kernel.cache_warmer, priority: 20}]