services:

    # Uploads 目录操作
    phpdish.media.file_manager:
       class: PHPDish\Component\Media\Manager\FileManager
       arguments: ['@phpdish.filesystem.uploads']

    phpdish.media.file_namer:
       class: PHPDish\Component\Media\Namer\DatePathNamer
       arguments: ['@phpdish.filesystem.uploads']

    phpdish.media.url_builder:
       class: PHPDish\Component\Media\UrlBuilder\GeneralBuilder
       arguments: ['@liip_imagine.cache.manager', '%app.path.uploads%']

    phpdish.media.file_factory:
        class: PHPDish\Component\Media\Manager\FileFactory
        arguments: ['@phpdish.media.file_namer']

    phpdish.media.file_uploader:
       class: PHPDish\Component\Media\Uploader\FileUploader
       arguments: ['@phpdish.media.file_factory',  '@phpdish.media.file_manager']

    phpdish.media.file_downloader:
       class: PHPDish\Component\Media\Downloader\FileDownloader
       arguments: ['@phpdish.http_client', '@phpdish.media.file_manager',  '@phpdish.media.file_namer']

    phpdish.media.twig_extension:
        class: PHPDish\Bundle\MediaBundle\Twig\MediaExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension}