services:
    # Uploads 目录操作
    phpdish_media.file_manager:
       class: PHPDish\Component\Media\Manager\FileManager
       arguments: ['@phpdish_media.filesystem.uploads']

    phpdish_media.file_namer:
       class: PHPDish\Component\Media\Namer\DatePathNamer
       arguments: ['@phpdish_media.filesystem.uploads']

    phpdish_media.url_builder:
       class: PHPDish\Component\Media\UrlBuilder\GeneralBuilder
       arguments: ['@liip_imagine.cache.manager', '%app.path.uploads%']

    phpdish_media.file_factory:
        class: PHPDish\Component\Media\Manager\FileFactory
        arguments: ['@phpdish_media.file_namer']

    phpdish_media.file_uploader:
       class: PHPDish\Component\Media\Manager\FileUploader
       arguments: ['@phpdish_media.file_factory',  '@phpdish_media.file_manager']

    phpdish_media.file_downloader:
       class: PHPDish\Component\Media\Manager\FileDownloader
       arguments: ['@phpdish_core.http_client', '@phpdish_media.file_manager',  '@phpdish_media.file_factory']

    phpdish_media.twig_extension:
        class: PHPDish\Bundle\MediaBundle\Twig\MediaExtension
        arguments: ['@service_container', '%cdn.host%']
        tags: ['twig.extension']

    ## CDN 处理
    phpdish_media.imagine.resolver:
        class: PHPDish\Bundle\MediaBundle\Imagine\CDNResolver
        parent: liip_imagine.cache.resolver.prototype.web_path
        arguments:
            $webRootDir: '%kernel.root_dir%/../web'
            $cachePrefix: media/cache
            $baseUrl: '%cdn.host%'
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: phpdish_media.imagine_resolver }

    ## 给oneup uploader使用
    phpdish_media.oneup_file_namer:
       class: PHPDish\Bundle\MediaBundle\Oneup\Naming\GenericNamer
       parent: 'phpdish_media.file_namer'
       public: true