PHPDish\Bundle\CoreBundle\Entity\Comment:
    exclusion_policy: ALL
    properties:
        body:
            expose: true
            type: string
            groups: [Default, Detailed]
        originalBody:
            expose: true
            type: string
            groups: [Default, Detailed]
        enabled:
            expose: true
            type: boolean
            groups: [Default, Detailed]
        createdAt:
            expose: true
            type: DateTime
            groups: [Default, Detailed]
        updatedAt:
            expose: true
            type: DateTime
            groups: [Default, Detailed]
        user:
            expose: true
            type: PHPDish\Bundle\UserBundle\Entity\User
            groups: [Detailed]