services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    phpdish.manager.thread:
       class: PHPDish\Bundle\ForumBundle\Service\ThreadManager
       public: true
       arguments: ['', "@doctrine.orm.entity_manager", "@phpdish.pinyin_translator"]

    phpdish.manager.topic:
        class: PHPDish\Bundle\ForumBundle\Service\TopicManager
        arguments: ['', '@doctrine.orm.entity_manager', '@event_dispatcher', '@phpdish.body_processor']
        public: true

    phpdish.manager.reply:
        class: PHPDish\Bundle\ForumBundle\Service\ReplyManager
        public: true
        arguments: ['', "@doctrine.orm.entity_manager", '@event_dispatcher', "@phpdish.body_processor"]

    phpdish.form.data_transformer.string_to_threads:
        class: PHPDish\Bundle\ForumBundle\Form\DataTransformer\StringToThreadsTransformer
        arguments: ["@phpdish.manager.thread"]

    phpdish.form.topic_type:
        class: PHPDish\Bundle\ForumBundle\Form\Type\TopicType
        arguments: ["@phpdish.form.data_transformer.string_to_threads"]
        tags:
           - {name: "form.type"}

    phpdish.security.topic_voter:
        class: PHPDish\Bundle\ForumBundle\Security\TopicVoter
        arguments:
            - "@security.access.decision_manager"
        tags:
            - {name: "security.voter"}
        public: false

    phpdish.security.topic_reply_voter:
        class: PHPDish\Bundle\ForumBundle\Security\TopicReplyVoter
        arguments:
            - "@security.access.decision_manager"
        tags:
            - {name: "security.voter"}
        public: false

    phpdish.security.thread_voter:
        class: PHPDish\Bundle\ForumBundle\Security\ThreadVoter
        arguments:
            - "@security.access.decision_manager"
        tags:
            - {name: "security.voter"}
        public: false

    phpdish.twig_extension.topic:
        class: PHPDish\Bundle\ForumBundle\Twig\TopicExtension
        public: false
        arguments:
            - "@phpdish.manager.thread"
            - "@phpdish.manager.topic"
            - "@phpdish.manager.reply"
        tags:
            - {name: twig.extension}

    phpdish.doctrine.orm.entity_listener.topic:
        class: PHPDish\Bundle\ForumBundle\EventListener\TopicListener
        public: false
        arguments: ['@phpdish.manager.topic', '@phpdish.manager.user']
        tags:
            - {name: doctrine.orm.entity_listener, entity: PHPDish\Bundle\ForumBundle\Model\Topic, event: postPersist, method: postPersist}

    PHPDish\Bundle\ForumBundle\Controller\:
         resource: "../../Controller"
         arguments:
              $configuration: '@phpdish.resource.configuration.phpdish_forum'
         tags: ['controller.service_arguments']