imports:
   - {resource: '@PHPDishCmsBundle/Resources/config/config.yml'}
   - {resource: '@PHPDishMediaBundle/Resources/config/config.yml'}
   - {resource: 'phpdish.yml'}

doctrine:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                   gedmo_tree:
                      type: annotation
                      prefix: Gedmo\Tree\Entity
                      dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                      alias: GedmoTree
                      is_bundle: false

## doctrine 扩展
stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            tree: true
            timestampable: true

# KNP Menu
knp_menu:
    twig:
        template: KnpMenuBundle::menu.html.twig
    templating: false
    default_renderer: twig

## FOSUser
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: PHPDish\Bundle\CoreBundle\Model\User
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    resetting:
        email:
            template: 'PHPDishWebBundle:Resetting:email.html.twig'
    registration:
        form:
            type: PHPDish\Bundle\UserBundle\Form\Type\RegistrationType

# FOSRest
fos_rest:
    routing_loader:
        default_format: json
    view:
#        mime_types:
#            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1', 'application/json;version=1.2']
        view_response_listener: false
        formats:
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig

    format_listener:
        rules:
            - { path: ^/, priorities: [ html, json ], fallback_format: ~, prefer_extension: true }

# FOSMessage
fos_message:
    db_driver: orm
    thread_class: PHPDish\Bundle\CoreBundle\Model\MessageThread
    message_class: PHPDish\Bundle\CoreBundle\Model\Message

httplug:
    plugins:
        logger: ~
    clients:
        default:
            factory: 'httplug.factory.guzzle6'
            plugins: ['httplug.plugin.logger']
            config:
                verify: false
                timeout: 20

# Algolia 搜索
algolia_search:
    prefix: staging
    indices:
        - name: posts
          class: PHPDish\Bundle\PostBundle\Model\Post
          enable_serializer_groups: true

        - name: topics
          class: PHPDish\Bundle\ForumBundle\Model\Topic
          enable_serializer_groups: true

        - name: users
          class: PHPDish\Bundle\UserBundle\Model\User
          enable_serializer_groups: true

## 验证码
gregwar_captcha:
   as_url: true
   quality: 70
   length: 5

## Js Translator
bazinga_js_translation:
    locale_fallback: '%locale%'
    default_domain: assets

# Media
knp_gaufrette:
    adapters:
        uploads:
            local:
                directory: '%app.dir.uploads%'
                create: true
        avatar:
            local:
                directory: '%app.dir.avatar%'
                create: true

    filesystems:
        local:
          adapter: uploads
          alias: phpdish_media.filesystem.uploads
        avatar:
          adapter: avatar
          alias: phpdish_media.filesystem.avatar


# Liip Imagine
liip_imagine:
    cache: phpdish_media.imagine_resolver
    loaders:
        default:
            filesystem:
                data_root:
                  - '%app.dir.uploads%'
                  - '%app.dir.avatar%'
#    resolvers:
#        default:
#            web_path: ~

    filter_sets:
        cache: ~
        # the name of the "filter set"
        middle_square:
            quality: 75
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
                background: { size: [120, 120], position: center, color: '#ffffff' }

        middle_rectangle:
            quality: 75
            filters:
                thumbnail: { size: [220, 300], mode: outbound }
                background: { size: [220, 300], position: center, color: '#ffffff' }

phpdish_media:
    imagine_resolver:
         cdn_host: '%cdn.host%'
    mappings:
        avatar:
            filesystem_service: phpdish_media.filesystem.avatar
            base_url: '%app.path.avatar%'
        uploads:
            filesystem_service: phpdish_media.filesystem.uploads
            base_url: '%app.path.uploads%'
    default_mapping: uploads

# 文件上传
oneup_uploader:
    mappings:
        uploads:
            root_folder: true
            namer: phpdish_media.oneup_file_namer.uploads
            storage:
                type: gaufrette
                filesystem: phpdish_media.filesystem.uploads
                sync_buffer_size: 1M
            frontend: plupload
            use_orphanage: false

# 支付
phpdish_payment:
    youzan:
      client_id: '%youzan.client_id%'
      client_secret: '%youzan.client_secret%'
      kdt_id: '%youzan.kdt_id%'
