phpdish_user:
    resources:
        user:
            model: PHPDish\Bundle\CoreBundle\Model\User
        profile:
            model: PHPDish\Bundle\CoreBundle\Model\Profile
        point_history:
            model: PHPDish\Bundle\CoreBundle\Model\PointHistory


phpdish_chat:
    resources:
        message:
            model: PHPDish\Bundle\CoreBundle\Model\Message
        message_metadata:
            model: PHPDish\Bundle\CoreBundle\Model\MessageMetadata
        message_thread:
            model: PHPDish\Bundle\CoreBundle\Model\MessageThread
        message_thread_metadata:
            model: PHPDish\Bundle\CoreBundle\Model\MessageThreadMetadata

phpdish_post:
    resources:
        post:
            model: PHPDish\Bundle\CoreBundle\Model\Post
        category:
            model: PHPDish\Bundle\CoreBundle\Model\Category
        comment:
            model: PHPDish\Bundle\CoreBundle\Model\Comment

phpdish_forum:
    resources:
        topic:
            model: PHPDish\Bundle\CoreBundle\Model\Topic
        thread:
            model: PHPDish\Bundle\CoreBundle\Model\TopicThread
        reply:
            model: PHPDish\Bundle\CoreBundle\Model\TopicReply

phpdish_payment:
    resources:
        payment:
            model: PHPDish\Bundle\CoreBundle\Model\Payment
        wallet:
            model: PHPDish\Bundle\CoreBundle\Model\Wallet