## 媒体处理bundle

phpdish_media:
    imagine_resolver:
         cdn_host: '%cdn.host.web%'
    mappings:
        avatar:
            filesystem_service: phpdish_media.filesystem.avatar
            base_url: '%app.path.avatar%'
        uploads:
            filesystem_service: phpdish_media.filesystem.uploads
            base_url: '%app.path.uploads%'
    default_mapping: uploads
    
## 用户
phpdish_user:
    avatar_downloader: 'phpdish_media.file_downloader.avatar'
    
# 支付
phpdish_payment:
    youzan:
      client_id: '%youzan.client_id%'
      client_secret: '%youzan.client_secret%'
      kdt_id: '%youzan.kdt_id%'

# 多主题
phpdish_theme:
   current_theme: '%theme.current_theme%'
   theme_directory: '%kernel.project_dir%/themes'
   namespaces: ['PHPDishWebBundle']
   
## 资源处理，见 phpdish.yml
phpdish_resource:
    templates_namespace: PHPDishWebBundle

## 运营核心
phpdish_core:
    assets:
        web:
            cdn_host: '%cdn.host.web%'
        admin:
            cdn_host: '%cdn.host.admin%'